# Generated by Django 3.2.9 on 2021-12-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shop_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published', models.DateField()),
                ('pages', models.IntegerField()),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non Fiction'), ('Detective', 'Detective'), ('Horror', 'Horror'), ('Comedy', 'Comedy')], default='Non-fiction', max_length=255)),
                ('cover_type', models.CharField(choices=[('Hard', 'Hard'), ('Soft', 'Soft')], default='Hard', max_length=100)),
                ('amount_limit', models.IntegerField()),
                ('time_limit', models.DateTimeField()),
            ],
        ),
    ]
