# Generated by Django 3.2.9 on 2021-12-23 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.shop'),
            preserve_default=False,
        ),
    ]
